# Generated by Django 3.1.2 on 2020-10-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('remitente', models.EmailField(max_length=254)),
                ('cc_myself', models.BooleanField()),
            ],
        ),
    ]
