# Generated by Django 3.1.2 on 2020-10-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contacto_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='destinatario',
        ),
    ]
