# Generated by Django 3.1.2 on 2020-10-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.persona')),
            ],
        ),
    ]
