# Generated by Django 3.1.2 on 2020-11-06 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('escuchar música', 'Escuchar música'), ('leer', 'Leer'), ('escribir', 'Escribir'), ('pintar', 'Pintar')], max_length=50), size=None),
        ),
    ]
