# Generated by Django 3.1.2 on 2020-11-09 01:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20201108_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='hobbies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('escuchar música', 'Escuchar música'), ('leer', 'Leer'), ('escribir', 'Escribir'), ('pintar', 'Pintar')], max_length=36),
        ),
    ]
