# Generated by Django 3.1.2 on 2020-11-09 02:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20201108_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='hobbies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('escuchar música', 'Escuchar música'), ('leer', 'Leer'), ('escribir', 'Escribir'), ('pintar', 'Pintar')], max_length=36, null=True),
        ),
    ]
